### PR TITLE
Run BQ job to pre-render Display Activation

### PR DESCRIPTION
**Pull request by olegrise**
@alexey-rise please review. Basically the `prerender` task is chained to run after `extract` is completed.

### CODE REVIEW

**Comment by alexey-rise** [comment]
@olegrise overall comment: I think it would be better if you cloned the display log extractor app and created a new app that caches display activation ratio query into a table instead of trying to make the existing app run another query as well as the original one. This way it would be easy to disable one job without affecting the other (we might at some point in the future decide that we don't need either one of the 2 queries). What do you think?

**Comment by olegrise** [comment]
@alexey-rise I was actually thinking in opposite direction. These two queries have to run in sequence one after another and having them in one module makes implementation simpler. In fact there are two more queries which would benefit from pre-rendering and I was thinking that it would be very easy to add them to this module if we have to. I don't think it makes sense to add a new GAE module for each query, but I agree that it makes sense to structure the code in way so it's easy to add/remove queries. 

In any case, at this point it's hard to tell if we are going to touch this module ever again and if we do, then what problem we would try to solve. In other words because we don't have big plans for this module in the future, it's hard to tell which direction to pick at this moment. I would just leave it as is for now. You concur?

**Comment by alexey-rise** [comment]
@olegrise there is really no penalty for adding modules in GAE :-) so we *could* have a module per query if we wanted.

My concern is: these apps/modules are different from something like say Store Server which we keep developing continuously and at least one person is very comfortable with making changes to it at any point in its lifecycle. 
On the other hand these stats/queries support apps are developed and left to run for years  and then if we ever need to make changes to them nobody really remembers how they work and what to do/not to do (easy example: if you run "extract" job right now to test your "prerender" job on production the display activity data for that day will be duplicated and multiple charts/dashboards will be affected and since there is no "delete" in BQ you would have to delete and re-create the whole display activity table from scratch which would be quite costly).  

For this reason I would much prefer to leave these apps "sealed" once they are deployed and are working as expected and never touch them unless the changes are absolutely necessary. I don't think that the order of queries makes changing the display extractor app *absolutely* necessary (you can just as easily have them run in sequence by scheduling the display activation query to run X min later in cron). 

I know it may seem easier to add a query than to create a new app for a new query but it makes the app more complex and less reliable every time we do that and I would argue that reliability and simplicity are the most important for these kinds of apps. I also realize that adding just one more query doesn't make the app that much more complex, but I think it's better to be consistent from the beginning.

**Comment by olegrise** [comment]
Closing this PR. This functionality has been move to [display-activation-prerenderer](https://github.com/Rise-Vision/display-activation-prerenderer) module.

**Pull request closed without merging**
